name: GitHubBrowserSample
options:
  xcodeVersion: "12.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: 5.0

packages:
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    version: 0.5.0
  NukeUI:
    url: https://github.com/kean/NukeUI
    version: 0.6.2    

targets:
  GitHubBrowserSample:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.example.app.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "\"Sources/Resources/Preview Content\""
        OTHER_LDFLAGS: $(inherited) -framework Shared
        FRAMEWORK_SEARCH_PATHS: $(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
    sources:
      - path: Sources
      - path: Sources/DI/NeedleGenerated.swift
        optional: true
        createIntermediateGroups: true      
    dependencies:
      - package: CombineSchedulers
      - package: NukeUI
      - package: NukeUI
        product: Nuke
      - carthage: NeedleFoundation  
    preBuildScripts:
      - name: Pack for Xcode
        script: ./scripts/packforxcode.sh
      - name: Run needle
        outputFiles:
          - $SRCROOT/Sources/DI/NeedleGenerated.swift
        script:  ./scripts/needle.sh        
    postCompileScripts:
      - name: Run SwiftFormat
        script: ./scripts/swiftformat.sh
      - name: Run SwiftLint
        script: ./scripts/swiftlint.sh

schemes:
  GitHubBrowserSample:
    build:
      targets:
        GitHubBrowserSample: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug      